ingresscontroller pkg added
openshift-kni/eco-goinfra pull request #163
Opened 2023-10-16 21:10 UTC by elenagerman

ingresscontroller pkg added

2023-10-17 20:36 UTC, achuzhoy commented on pkg/ingresscontroller/ingresscontroller.go
> +// Builder provides a struct for ingresscontroller object from the cluster and a ingresscontroller definition.
nit: and an ingresscontroller

2023-10-17 20:37 UTC, achuzhoy commented on pkg/ingresscontroller/ingresscontroller.go
> +	glog.V(100).Infof("Pulling existing ingresscontroller with name %s under namespace %s from cluster",
Fetching

2023-10-17 20:39 UTC, achuzhoy commented
Looks good to me apart from some minor comments

2023-10-18 13:43 UTC, achuzhoy commented
/lgtm

2023-10-18 16:13 UTC, kononovn commented on pkg/ingresscontroller/ingresscontroller.go
> +	ingresscontrollerNamespase = "openshift-ingress-operator"
Please remove this constant. It should be parameter. You can have this constant in test code

2023-10-18 16:14 UTC, kononovn commented on pkg/ingresscontroller/ingresscontroller.go
> +	ingresscontrollerName      = "default"
Please remove this constant. It should be parameter. You can have this constant in test code

2023-10-18 16:14 UTC, kononovn commented on pkg/ingresscontroller/ingresscontroller.go
> +func Pull(apiClient *clients.Settings) (*Builder, error) {
Please add name and nsname to this function

2023-10-18 16:16 UTC, kononovn commented on pkg/ingresscontroller/ingresscontroller.go
> +package ingresscontroller
Please rename package to ingress and directory ./pkg/ingress. Under ingress we could have several resources like:
1. Ingress
2. Ingresscontroller 
and more

2023-10-18 16:17 UTC, kononovn commented on pkg/ingresscontroller/ingresscontroller.go
> +
Please add Delete function.

2023-10-18 16:18 UTC, kononovn requested changes
Overall looks good, just few comments

2023-10-19 00:57 UTC, kononovn commented on pkg/ingress/ingresscontroller.go
> +	glog.V(100).Infof("Updating the Builder %s in namespace %s",
Please change log to "Updating the ingresscontroller %s in namespace...."

2023-10-19 00:58 UTC, kononovn approved these changes
apart 2 comments above **lgtm**

2023-10-19 02:26 UTC, kononovn commented
@elenagerman Please fix 2 minor comments above and I'll merge this PR

2023-10-19 13:03 UTC, merged