pod: add new WithLabels method
openshift-kni/eco-goinfra pull request #171
Opened 2023-10-20 14:25 UTC by jmontesi

The existing `WithLabel` method only allows to add one label to a Pod's definition. If more want to be added the old ones will be overwritten. This new method accepts a set of labels in the form of a `map` to define all the labels required at once.

Also, the `isMutationAllowed` and the `isMountAlreadyInUseInPod` methods haven been modified to return a `bool` as the name suggests. This has been used in the different `With*` methods to leave as early as possible if the right condition is not satisfied.

2023-10-20 14:41 UTC, kononovn requested changes
@jmontesi Thanks for the contribution. Let's change this PR a bit.
Can you please just add single WithLabels function to this PR.

As for isMutationAllowed change we need to create issue and discuss it. If it's going to be accepted we'll need to refactor **all** packages under this project because this design pattern is applied across all packages and not in single pod pkg.

2023-10-23 13:00 UTC, kononovn requested changes
Overall looks good. Just 1 comment to fix.

2023-10-23 13:54 UTC, jmontesi commented on pkg/pod/pod.go
> +
Done.

2023-10-23 14:24 UTC, kononovn submitted a review, later dismissed
/lgtm

2023-10-23 19:09 UTC, kononovn approved these changes

2023-10-23 19:09 UTC, merged