Added cluster-group-upgrade package
openshift-kni/eco-goinfra pull request #180
Opened 2023-11-05 13:06 UTC by shaior

2023-11-06 16:45 UTC, trewest commented on pkg/cgu/cgu.go
> +
```suggestion
	if err == nil {
		builder.Object = builder.Definition
	}
```

2023-11-06 16:46 UTC, trewest commented on pkg/cgu/list.go
> +func ListCgusInAllNamespaces(apiClient *clients.Settings, options metaV1.ListOptions) ([]*CguBuilder, error) {
```suggestion
func ListInAllNamespaces(apiClient *clients.Settings, options metaV1.ListOptions) ([]*CguBuilder, error) {
```

2023-11-06 16:46 UTC, trewest commented on pkg/cgu/list.go
> +func ListCgusInAllNamespaces(apiClient *clients.Settings, options metaV1.ListOptions) ([]*CguBuilder, error) {
Please use the options parameter that is being provided

2023-11-06 16:47 UTC, trewest commented on pkg/cgu/list.go
> +	policyList := &v1alpha1.ClusterGroupUpgradeList{}
```suggestion
	cguList := &v1alpha1.ClusterGroupUpgradeList{}
```

2023-11-06 16:47 UTC, trewest requested changes
Few comments

2023-11-08 15:09 UTC, trewest requested changes
Just one change and we can merge

2023-11-08 20:50 UTC, trewest commented
@shaior can you resolve the merge conflicts? Other than that, looks good. Waiting for one more approval

2023-11-09 09:48 UTC, cdvultur requested changes
Small filename change, for consistency
Otherwise it looks great !

2023-11-09 10:30 UTC, cdvultur approved these changes
/lgtm

2023-11-09 14:04 UTC, trewest approved these changes
/lgtm

2023-11-09 14:07 UTC, merged