Methods for node cordoning/uncordoning and drain
openshift-kni/eco-goinfra pull request #229
Opened 2024-01-25 16:41 UTC by yprokule

Methods for nodes cordoning, uncordoning and draining added

2024-01-26 15:48 UTC, kononovn commented on pkg/nodes/drain.go
> +func NewDrainHelperBuilder(
I think:
Drain/Cordon/Uncordon functions have to a part of node.Builder struct.
Please add these methods as part of Builder in node.go file

2024-01-26 15:53 UTC, kononovn requested changes
Please check comment above

2024-01-29 16:21 UTC, kononovn requested changes
PR looks good. It's almost ready to merge.
Can you please do following changes:

Lave 2 commits instead of 3 commits under this PR.
 
The first commit has to have following message:
"Bump dependence. Add kubectl drain lib"
Second commit message:
"Updated client.go. Added K8sClient to clients struct."

2024-01-29 18:33 UTC, trewest approved these changes
/lgtm

2024-01-29 18:34 UTC, merged