Added catalogsource to olm pkg
openshift-kni/eco-goinfra pull request #231
Opened 2024-01-28 14:46 UTC by shaior

2024-01-29 14:25 UTC, trewest commented on pkg/olm/catalogsourcelist.go
> +func ListCatalogSource(
```suggestion
func ListCatalogSources(
```

2024-01-29 14:25 UTC, trewest commented on pkg/olm/catalogsourcelist.go
> +	csvList, err := apiClient.OperatorsV1alpha1Interface.CatalogSources(nsname).List(
```suggestion
	catalogSourceList, err := apiClient.OperatorsV1alpha1Interface.CatalogSources(nsname).List(
```

2024-01-29 14:26 UTC, trewest commented on pkg/olm/catalogsourcelist.go
> +		glog.V(100).Infof("Failed to list catalogsources in the nsname %s due to %s", nsname, err.Error())
```suggestion
		glog.V(100).Infof("Failed to list catalogsources in the namespace %s due to %s", nsname, err.Error())
```

2024-01-29 14:26 UTC, trewest requested changes
Just a few comments. Overall looks good

2024-01-29 14:58 UTC, trewest commented on pkg/olm/catalogsourcelist.go
> +		glog.V(100).Infof("Failed to list catalogsources in the nsname %s due to %s", nsname, err.Error())
@shaior I still see this as nsname

2024-01-29 15:18 UTC, shaior commented on pkg/olm/catalogsourcelist.go
> +		glog.V(100).Infof("Failed to list catalogsources in the nsname %s due to %s", nsname, err.Error())
Fixed, thanks.

2024-01-29 15:27 UTC, trewest approved these changes
/lgtm

2024-01-29 16:30 UTC, kononovn commented on pkg/olm/catalogsource.go
> +	// CatalogSourceBuilder definition. Used to create
Please update it to CatalogSource definition. Under Definition we keep CatalogSource only.

2024-01-29 16:31 UTC, kononovn commented on pkg/olm/catalogsource.go
> +	// CatalogSourceBuilder object with minimum set of required elements.
Same as above

2024-01-29 16:32 UTC, kononovn commented on pkg/olm/catalogsource.go
> +func PullCatalogSource(apiClient *clients.Settings, name, namespace string) (*CatalogSourceBuilder,
Please change namespace to nsname. Same as we have in other packages.

2024-01-29 16:33 UTC, kononovn commented on pkg/olm/catalogsourcelist.go
> +	namespace string,
Please change var name to nsname

2024-01-29 16:34 UTC, kononovn requested changes
@shaior overall looks good, thanks for you contribution. Just few minor changes are required.

2024-01-30 09:26 UTC, shaior commented on pkg/olm/catalogsource.go
> +func (builder *CatalogSourceBuilder) Delete() error {
As we spoke on Slack, I tried to delete one and it was immediately deleted. 
if it will be required it can be added in future PRs.

2024-01-30 15:37 UTC, merged