IBU: Allow setting timeout for initMonitor
openshift-kni/eco-goinfra pull request #256
Opened 2024-02-26 14:46 UTC by achuzhoy

This allows controlling how long to wait before
the autorollback is attempted. Default is 1800 seconds.

2024-02-27 14:59 UTC, kononovn requested changes
Please check comment above

2024-02-27 15:01 UTC, achuzhoy commented on pkg/lca/imagebasedupgrade.go
> +	seconds int) *ImageBasedUpgradeBuilder {
See comments on https://issues.redhat.com/browse/OCPBUGS-29483

I think we should allow it to catch possible errors.

2024-02-27 16:39 UTC, kononovn commented on pkg/lca/imagebasedupgrade.go
> +	seconds int) *ImageBasedUpgradeBuilder {
No, If you want to test negative scenarios you have to mutate struct directly in your test case with relevant comment. In eco-goinfra project we keep only correct configuration.

2024-02-27 17:46 UTC, achuzhoy commented on pkg/lca/imagebasedupgrade.go
> +	seconds int) *ImageBasedUpgradeBuilder {
Updated.Thanks.

2024-02-28 14:43 UTC, kononovn approved these changes
/lgtm

2024-02-28 14:54 UTC, cdvultur approved these changes
/lgtm

2024-02-28 14:55 UTC, merged