Kmm intreemodules update given CRD changes
openshift-kni/eco-goinfra pull request #277
Opened 2024-03-19 11:01 UTC by cdvultur

KMM has deprecated the `InTreeModuleToRemove` and moved it to be a list 
- Updated existing WithInTreeModuleToRemove to ensure compatibility on existing tests 
- Added new WithInTreeModulesToRemove
- Pulled new v1beta2 in vendor 

See: https://github.com/rh-ecosystem-edge/kernel-module-management/blob/main/api/v1beta1/module_types.go#L121 for details

2024-03-19 14:47 UTC, cdvultur commented on pkg/kmm/kernelmapping.go
> +// WithInTreeModulesToRemove adds a list of modules to be removed to KernelMapper.
No. This relates to https://github.com/rh-ecosystem-edge/kernel-module-management/blob/main/api/v1beta1/module_types.go#L130 

```
	// +optional
	// InTreeModulesToRemove specifies any number of  in-tree kernel modules that should be removed (if present)
	// before loading the kernel module from the ContainerImage
	InTreeModulesToRemove []string `json:"inTreeModulesToRemove"`
```

I will leave it as if to stick to the `With<Field>` pattern

2024-03-19 14:57 UTC, achuzhoy submitted a review, later dismissed

2024-03-19 14:57 UTC, achuzhoy commented
/lgtm

2024-03-20 17:57 UTC, kononovn commented
@cdvultur This PR breaks client functionality due to dependency issue.

2024-03-20 17:57 UTC, kononovn requested changes
This PR is the root cause of deps conflict .

2024-03-21 15:46 UTC, cdvultur commented
closing it for the moment.

2024-03-21 15:46 UTC, closed without merging