sriov pkg: Added NetworkPoolConfig
openshift-kni/eco-goinfra pull request #307
Opened 2024-03-28 16:54 UTC by evgenLevin

2024-03-28 17:33 UTC, sebrandon1 reviewed
Just some comments about returns and early-returns to allow for easier unit testing in future.

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```suggestion
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```

Per #239

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +		builder.errorMsg = "SriovNetworkPoolConfig 'nodeSelector' cannot be empty map"
```suggestion
		builder.errorMsg = "SriovNetworkPoolConfig 'nodeSelector' cannot be empty map"
		
		return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +				builder.errorMsg = fmt.Sprintf("invalid value %q: %v", maxUnavailable.StrVal, err)
```suggestion
				builder.errorMsg = fmt.Sprintf("invalid value %q: %v", maxUnavailable.StrVal, err)
				return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	}
Not needed if returns are in place after setting `builder.errorMsg`.

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +				builder.errorMsg = fmt.Sprintf("invalid value: percentage needs to be between 1 and 100: %v", maxUnavailable)
```suggestion
				builder.errorMsg = fmt.Sprintf("invalid value: percentage needs to be between 1 and 100: %v", maxUnavailable)
				return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +			builder.errorMsg = fmt.Sprintf("invalid type: strings needs to be a percentage: %v", maxUnavailable)
```suggestion
			builder.errorMsg = fmt.Sprintf("invalid type: strings needs to be a percentage: %v", maxUnavailable)
			
			return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +			builder.errorMsg = fmt.Sprintf("negative number is not allowed: %v", maxUnavailable)
```suggestion
			builder.errorMsg = fmt.Sprintf("negative number is not allowed: %v", maxUnavailable)
			
			return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +		builder.errorMsg = "SriovNetworkPoolConfig 'name' cannot be empty"
```suggestion
		return nil, errors.New("SriovNetworkPoolConfig 'name' cannot be empty")
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +		builder.errorMsg = "SriovNetworkPoolConfig 'namespace' cannot be empty"
```suggestion
		return nil, errors.New("SriovNetworkPoolConfig 'namespace' cannot be empty")
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +		builder.errorMsg = "SriovNetworkPoolConfig 'name' cannot be empty"
```suggestion
		builder.errorMsg = "SriovNetworkPoolConfig 'name' cannot be empty"
		
		return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +		builder.errorMsg = "SriovNetworkPoolConfig 'nsname' cannot be empty"
```suggestion
		builder.errorMsg = "SriovNetworkPoolConfig 'nsname' cannot be empty"
		
		return builder
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	return err
```suggestion
	return nil
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	return builder, err
```suggestion
	return builder, nil
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	return poolConfigBuilderObjects, err
```suggestion
	return poolConfigBuilderObjects, nil
```

2024-03-28 17:33 UTC, sebrandon1 commented on pkg/sriov/poolconfig.go
> +	apiClient *clients.Settings
Any chance to limit scope here?

#272 has an example.  If not that's fine.

2024-04-09 14:10 UTC, evgenLevin commented
@kononovn has been added. Several unit tests have failed, but none of them are related to this PR.

2024-04-11 17:29 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +	glog.V(100).Infof("Creating the SriovNetworkPoolConfig %s", builder.Definition.Name)
Please add namespace to log

2024-04-11 17:30 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +	glog.V(100).Infof("Deleting the SriovNetworkPoolConfig object %s", builder.Definition.Name)
Please add namespace to log

2024-04-11 17:30 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +	glog.V(100).Infof("Checking if SriovNetworkPoolConfig %s exists", builder.Definition.Name)
Please add namespace to log

2024-04-11 17:33 UTC, kononovn commented on pkg/sriov/poolconfig_test.go
> +func TestPullPoolConfig(t *testing.T) {
You test NewPoolConfigBuilder function here instead of Pull function

2024-04-11 17:35 UTC, kononovn requested changes
Please fix few comments above.

2024-04-11 19:59 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +		glog.V(100).Infof("Failed to get SriovNetworkPoolConfig %s", builder.Definition.Name)
Please add namespace

2024-04-11 19:59 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +	glog.V(100).Infof("Updating the SriovNetworkPoolConfig object %s", builder.Definition.Name)
Please add namespace

2024-04-11 19:59 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +		glog.V(100).Infof("Failed to update SriovNetworkPoolConfig %s", builder.Definition.Name)
Please add namespace

2024-04-11 20:00 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +		"Creating SriovNetworkPoolConfig %s with Node selector: %v", builder.Definition.Name, nodeSelector)
Please add namespace

2024-04-11 20:00 UTC, kononovn commented on pkg/sriov/poolconfig.go
> +		"Creating SriovNetworkPoolConfig %s with MaxUnavailable: %v", builder.Definition.Name, maxUnavailable)
Please add namespace

2024-04-11 20:01 UTC, kononovn commented on pkg/sriov/poolconfig_test.go
> +	testCases := []struct {
Please add test case when api client is nil.

2024-04-11 20:02 UTC, kononovn requested changes
Please fix few comments above.

2024-04-12 12:55 UTC, kononovn approved these changes
/lgtm

2024-04-12 13:17 UTC, merged