lca: Limiting the client for pull and newbuilder for lca
openshift-kni/eco-goinfra pull request #315
Opened 2024-04-03 18:11 UTC by achuzhoy

This is based on assignment
https://github.com/openshift-kni/eco-goinfra/issues/299

2024-04-03 19:08 UTC, achuzhoy commented
cc @trewest @kononovn

2024-04-03 19:08 UTC, achuzhoy commented
successfully tested

2024-04-03 22:02 UTC, sebrandon1 approved these changes

2024-04-03 22:03 UTC, sebrandon1 commented
It's interesting that the `Client` [variable](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/interfaces.go#L164) is actually an interface.

2024-04-04 16:27 UTC, trewest commented
> It's interesting that the Client [variable](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/interfaces.go#L164) is actually an interface.

@sebrandon1 I think [this](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/client.go#L223) is the underlying struct that implements Client. It's set [here](https://github.com/openshift-kni/eco-goinfra/blob/main/pkg/clients/clients.go#L181)

2024-04-04 20:01 UTC, trewest requested changes
Just one minor comment

2024-04-04 20:10 UTC, achuzhoy commented on pkg/lca/seedgenerator.go
> +	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
Updated. Thanks.

2024-04-04 20:13 UTC, trewest approved these changes
/lgtm

2024-04-04 21:01 UTC, merged