ocm: added new policy set builder and unit tests
openshift-kni/eco-goinfra pull request #341
Opened 2024-04-15 20:55 UTC by klaskosk

Added `NewPolicySetBuilder` as well as a method to add a new `Policy` to the set. Tests for the new methods are included.

2024-04-18 16:38 UTC, kononovn requested changes
Re-base is needed.

2024-04-18 17:34 UTC, klaskosk commented
@kononovn Rebased

2024-04-19 13:41 UTC, kononovn commented on pkg/ocm/policyset_test.go
> +func TestWithPolicy(t *testing.T) {
Please re-name to  TestPolicySetWithPolicy.

2024-04-19 13:43 UTC, kononovn requested changes
looks good, Just few comment to fix.

2024-04-19 14:51 UTC, klaskosk commented
@kononovn Thanks, I've made those changes

2024-04-19 17:54 UTC, kononovn approved these changes
/lgtm

2024-04-19 18:14 UTC, trewest approved these changes
/lgtm

2024-04-19 18:15 UTC, merged