cgu: add wait until backup starts function
openshift-kni/eco-goinfra pull request #359
Opened 2024-04-22 12:58 UTC by klaskosk

2024-04-22 13:58 UTC, kononovn commented on pkg/cgu/cgu.go
> +			return false, nil
Please add glog.V if error occurs

2024-04-22 13:58 UTC, kononovn commented on pkg/cgu/cgu.go
> +
Please add glog.V here as well

2024-04-22 17:27 UTC, klaskosk commented
@kononovn Added the logs and a test for the function. I modeled it after `TestWaitUntilCondition` in `deployment/deployment_test.go` but I'm not sure if it needs more test cases

2024-04-23 16:09 UTC, kononovn commented on pkg/cgu/cgu.go
> +			return false, nil
Please print error itself in the log as well. Add "due to: %w"

2024-04-23 16:09 UTC, kononovn commented on pkg/cgu/cgu.go
> +
Please print error itself in the log as well. Add "due to: %w"

2024-04-23 16:10 UTC, kononovn requested changes
Please fix few comments above.

2024-04-23 17:06 UTC, klaskosk commented
@kononovn Thanks, I've updated the logs to include the error

2024-04-23 17:28 UTC, kononovn approved these changes
/lgtm

2024-04-23 17:56 UTC, achuzhoy approved these changes

2024-04-23 17:56 UTC, achuzhoy commented
/lgtm

2024-04-23 17:56 UTC, merged