nto pkg: performanceprofile - new methods added, fixes and unit test added
openshift-kni/eco-goinfra pull request #430
Opened 2024-05-16 16:22 UTC by elenagerman

new methods: 
- WithNodeSelector
- WithGloballyDisableIrqLoadBalancing

2024-05-23 15:22 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +			expectedError:          "resourceVersion can not be set for Create requests",
This test case should't return error. It has to create object successfully. You just need to remove resourceVersion from structure

2024-05-23 15:22 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +			expectedError:          fmt.Errorf("PerformanceProfile cannot be deleted because it does not exist"),
Please change Delete method. 
We have to return nil and set Object to nil if actual object doesn't exist on cluster.

2024-05-23 15:24 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError     bool
You can remove this var and you
if expectedErrorText != "" instead.

2024-05-23 15:24 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError                 bool
Please remove this var. Same as above.

2024-05-23 15:24 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError     bool
Please remove this var same as above.

2024-05-23 15:25 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError     bool
Please remove this var.

2024-05-23 15:25 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError     bool
Please remove this var.

2024-05-23 15:26 UTC, kononovn commented on pkg/nto/performanceprofile_test.go
> +		expectedError       bool
Please remove this var.

2024-05-23 15:27 UTC, kononovn requested changes
Please re-base on top of the latest main.

2024-05-27 12:45 UTC, yprokule commented on pkg/nto/performanceprofile.go
> +		return builder
ditto

2024-05-27 20:12 UTC, kononovn submitted a review, later dismissed
/lgtm

2024-05-28 08:44 UTC, yprokule commented on pkg/nto/performanceprofile.go
> +		return builder
please move it to the _topologyPolicy_ assertion clause above

2024-05-28 08:55 UTC, yprokule commented on pkg/nto/performanceprofile_test.go
> +			testPages:         []v2.HugePage{},
I'd consider adding 2 more tests:
* explicitly asking for 2 different NUMA nodes
```
        defaultHugePagesNodeOne = int32(0)
        defaultHugePagesNodeTwo = int32(1)
	defaultHugepages              = []v2.HugePage{
 		{
 			Size:  "2M",
 			Count: 32768,
 			Node:  &defaultHugePagesNodeOne,
 		},
                {
 			Size:  "2M",
 			Count: 32768,
 			Node:  &defaultHugePagesNodeTwo,
 		},
 	}
```
* not asking for a NUMA node
```
	defaultHugepages              = []v2.HugePage{
 		{
 			Size:  "2M",
 			Count: 32768,
 		},
        }
```

2024-05-28 09:22 UTC, cdvultur submitted a review, later dismissed
/lgtm

2024-05-28 14:22 UTC, merged