secret: added package unit tests
openshift-kni/eco-goinfra pull request #440
Opened 2024-05-28 14:23 UTC by eldar101

Unittests for the secret package.

2024-06-19 12:22 UTC, achuzhoy commented on pkg/secret/secret_test.go
> +			secretType:           "test",
redunant.

2024-06-19 12:24 UTC, achuzhoy commented on pkg/secret/secret_test.go
> +		{
Redundant?

2024-06-19 12:40 UTC, achuzhoy commented on pkg/secret/secret_test.go
> +			secretType:           "test",
just secretType

2024-06-20 14:00 UTC, kononovn commented
@eldar101 Please re-base. There is new function in secret package

2024-06-21 13:13 UTC, kononovn commented on go.mod
> +	github.com/openshift-kni/eco-goinfra latest
Please remove this line from go.mod

2024-06-21 13:15 UTC, kononovn commented on pkg/secret/secret_test.go
> +
Please add test cases for following functions: NewBuilder, WithOptions, WithAnnotations, WithData, Update

2024-06-21 13:24 UTC, kononovn requested changes
Please check few comments above.

2024-06-24 14:52 UTC, kononovn requested changes
Please fix comments above

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +			secretType:         "",
I think we need to remove it.

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +		expectedErrorText   string
Please add client bool args. Refer to: https://github.com/openshift-kni/eco-goinfra/blob/5966cfaaf0378411c7307befc09a20b1e59e1df2/pkg/metallb/adresspool_test.go#L44
and Add 1 more test case when client is false(nil)

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestSecretCreate(t *testing.T) {
Please add 1 more test case when secret has invalid definition.
Refer to :https://github.com/openshift-kni/eco-goinfra/blob/5966cfaaf0378411c7307befc09a20b1e59e1df2/pkg/metallb/adresspool_test.go#L212

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestSecretValidate(t *testing.T) {
This is private function. Please move it to the end of the file

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestSecretGet(t *testing.T) {
Secret doesn't have Get function. Please remove it

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestSecrettWithOptions(t *testing.T) {
Please fix typo: TestSecre**tt**WithOptions> TestSecretWithOptions

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +	}
Empty function. Please write test function

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestSecretNewBuilder(t *testing.T) {
Please paste this function after TestSecretPull

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +                        namespace:     "",
namespace is empty instead of secretType. Please fix

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +	}
Test body is missing

2024-06-24 14:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +func TestUpdate(t *testing.T) {
Please re-name to TestSecretUpdate

2024-06-25 13:32 UTC, kononovn commented on pkg/secret/secret_test.go
> +		expectedErrorText   string
You added client but it's unused in test case.

2024-06-25 13:52 UTC, kononovn commented on pkg/secret/secret_test.go
> +		expectedErrorText   string
No, you have to add test case when you pass nil client to the Pull function and catch relevant error.
Please refer
https://github.com/openshift-kni/eco-goinfra/blob/5966cfaaf0378411c7307befc09a20b1e59e1df2/pkg/metallb/adresspool_test.go#L88

2024-06-25 13:53 UTC, kononovn requested changes
1 comment to fix

2024-06-25 13:53 UTC, kononovn commented
@eldar101 Please change commit message and PR headline to:

`secret: added package unit tests`

2024-06-26 13:21 UTC, kononovn commented
@eldar101 Please fix linter issues. Please run > make lint in order to make sure that basic check pass

2024-06-26 13:21 UTC, kononovn requested changes
please fix ci issues.

2024-06-27 13:39 UTC, kononovn commented
@eldar101 Check still failed. Please fix.

2024-07-03 14:29 UTC, trewest commented on pkg/secret/secret_test.go
> +		}
```suggestion
                assert.Equal(t, testCase.secretExistsAlready, testBuilder.Exists())
```

2024-07-03 14:48 UTC, trewest commented on pkg/secret/secret_test.go
> +		}
```suggestion
		data[testCase.key] = []byte(testCase.value)
		
		testBuilder.WithData(data)
		assert.Equal(t, testCase.expectedErr, testBuilder.errorMsg)

		if testCase.expectedErr == "" {
			assert.Equal(t, []byte(testCase.value), testBuilder.Definition.Data[testCase.key])
		}
```

2024-07-03 14:57 UTC, trewest commented on pkg/secret/secret_test.go
> +		result, err := testBuilder.Update()
It doesn't appear that you have actually updated the object with anything

2024-07-03 14:58 UTC, trewest commented on pkg/secret/secret_test.go
> +}
Please move these to the bottom of the file

2024-07-15 19:09 UTC, kononovn requested changes
Please fix few comments.

2024-07-15 19:09 UTC, kononovn commented on pkg/secret/secret_test.go
> +		expectedError       bool
You can remove this bool argument and use
if expectedErrorText != "" condition in test case.

2024-07-15 19:09 UTC, kononovn commented on pkg/secret/secret_test.go
> +		testSettings = clients.GetTestClients(clients.TestClientParams{
This is bug. Please check condition below and remove this line

2024-07-15 19:09 UTC, kononovn commented on pkg/secret/secret_test.go
> +		expectedError error
Please add client bool parameter and add 1 more scenario when client is nil.

2024-07-15 19:09 UTC, kononovn commented on pkg/secret/secret_test.go
> +		data := make(map[string][]byte)
Please move this map to test case parameters instead of key,value.

2024-07-16 14:39 UTC, kononovn approved these changes
/lgtm

2024-07-16 14:41 UTC, trewest approved these changes
/lgtm

2024-07-16 14:41 UTC, merged