Updated nodes package
openshift-kni/eco-goinfra pull request #45
Opened 2023-06-26 16:57 UTC by evgenLevin

2023-06-26 18:14 UTC, trewest requested changes
Few comments

2023-06-26 18:14 UTC, trewest commented on pkg/nodes/node.go
> +	err := builder.apiClient.Get(context.TODO(), goclient.ObjectKey{
shouldn't you use the typed client interface rather than the generic interface? Like was done in the Exists method previously?

2023-06-26 18:14 UTC, trewest commented on pkg/nodes/node.go
> +	glog.V(100).Infof("Waiting for the defined period until node %s is not unschedulable",
please add a validate block at the top of this method

2023-06-26 18:14 UTC, trewest commented on pkg/nodes/node.go
> +	if builder.errorMsg != "" {
this will be redundant when the validate block is added

2023-06-26 18:14 UTC, trewest commented on pkg/nodes/node.go
> +func (builder *NodeBuilder) WaitUntilNodeStable(timeout time.Duration) error {
I think a more appropriate name for this method is `WaitUntilSchedulable`. node is the name of the pkg so no need to add it to the method name.

2023-06-26 18:14 UTC, trewest commented on pkg/nodes/node.go
> +func (builder *NodeBuilder) WaitUntilNodeStable(timeout time.Duration) error {
You can then update subsequent logs/comments from `not unschedulable` to just `schedulable`

2023-06-26 19:05 UTC, kononovn commented on pkg/nodes/node.go
> +		if !node.Spec.Unschedulable {
I think you need to make sure that node is in Schedulable state for some specific period of time, sometimes we mark node as schedulable and them after 5 seconds move to unscheduled

2023-06-26 19:06 UTC, kononovn commented on pkg/nodes/node.go
> +		if !node.Spec.Unschedulable {
Please refer to: https://github.com/openshift-kni/eco-goinfra/blob/b2486f52938008d0fa468e4e38a852ec60e9027f/pkg/mco/mcp.go#L248

2023-06-26 19:07 UTC, kononovn requested changes
Please fix few comments above.

2023-06-26 19:34 UTC, kononovn commented
Commit message is very generic. Can you please add more specific info

2023-06-27 01:51 UTC, evgenLevin commented
@trewest @kononovn  PTAL one more time. Thanks!

2023-06-27 19:55 UTC, kononovn commented on pkg/nodes/node.go
> +		if !node.Spec.Unschedulable {
No you need to add 1 more PollImmediate function with additional stable timeout. Please check the reference link that I've share with you

2023-06-27 20:00 UTC, kononovn requested changes
Please check my comment above

2023-06-28 17:02 UTC, closed without merging