clusterlogging pkg: lokistack handler added
openshift-kni/eco-goinfra pull request #495
Opened 2024-06-28 23:31 UTC by elenagerman

2024-07-03 17:27 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-03 18:54 UTC, trewest commented on pkg/clusterlogging/lokistack.go
> +		"Setting lokiStack %s in namespace %s with the the storage class name config: %v",
```suggestion
		"Setting lokiStack %s in namespace %s with the storage class name: %s",
```

2024-07-03 18:54 UTC, trewest commented on pkg/clusterlogging/lokistack.go
> +		"Setting lokiStack %s in namespace %s with the the tenants config: %v",
```suggestion
		"Setting lokiStack %s in namespace %s with the tenants config: %v",
```

2024-07-03 18:54 UTC, trewest commented on pkg/clusterlogging/lokistack.go
> +		"Setting lokiStack %s in namespace %s with the the rules config: %v",
```suggestion
		"Setting lokiStack %s in namespace %s with the rules config: %v",
```

2024-07-03 18:55 UTC, trewest requested changes
Looks good just a few cosmetic changes

2024-07-03 21:45 UTC, elenagerman commented
> Looks good just a few cosmetic changes

Thanks!

2024-07-05 03:38 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-05 16:50 UTC, trewest commented on pkg/clusterlogging/lokistack.go
> +		glog.V(100).Infof("The nsname of the elasticsearch is empty")
```suggestion
		glog.V(100).Infof("The nsname of the lokiStack is empty")
```

2024-07-05 16:51 UTC, trewest approved these changes
/lgtm

2024-07-08 14:15 UTC, achuzhoy commented on pkg/clusterlogging/lokistack.go
> +		"Pulling lokiStack object name:%s in namespace: %s", name, nsname)
nit: 
```suggestion
		"Pulling lokiStack object name: %s in namespace: %s", name, nsname)
```

2024-07-08 14:24 UTC, achuzhoy commented on pkg/clusterlogging/lokistack.go
> +// NewLokiStackBuilder method creates new instance of builder.
```suggestion
// NewLokiStackBuilder creates new instance of builder.
```

2024-07-08 15:30 UTC, achuzhoy commented
/lgtm

2024-07-08 15:31 UTC, achuzhoy approved these changes

2024-07-08 17:13 UTC, merged