lso pkg: localvolumeset enhancements, unit test, new methods added
openshift-kni/eco-goinfra pull request #500
Opened 2024-07-05 03:34 UTC by elenagerman

localvolumeset enhancements, unit test, new methods added

2024-07-05 03:39 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-12 14:28 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +		"Adding tolerations to localVolumeSet %s in namespace %s; tolerations %v",
```suggestion
		"Adding tolerations %v to localVolumeSet %s in namespace %s",
```

2024-07-12 14:29 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +// WithStorageClassName sets the localVolumeSet operator's storageClassName.
```suggestion
// WithStorageClassName sets the localVolumeSet's storageClassName.
```

2024-07-12 14:30 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +		"Adding storageClassName to localVolumeSet %s in namespace %s; storageClassName %v",
```suggestion
		"Adding storageClassName %v to localVolumeSet %s in namespace %s",
```

2024-07-12 14:30 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +// WithVolumeMode sets the localVolumeSet operator's volumeMode.
```suggestion
// WithVolumeMode sets the localVolumeSet's volumeMode.
```

2024-07-12 14:30 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +		"Adding volumeMode to localVolumeSet %s in namespace %s; volumeMode %v",
```suggestion
		"Adding volumeMode %v to localVolumeSet %s in namespace %s",
```

2024-07-12 14:31 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +		"Adding volumeMode to localVolumeSet %s in namespace %s; volumeMode %v",
Same idea for the rest

2024-07-15 15:06 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-16 18:35 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +// WithTolerations sets the localVolumeSet's generation.
```suggestion
// WithTolerations sets the localVolumeSet's toleration.
```

2024-07-16 18:35 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +		glog.V(100).Infof("The tolerations is empty")
```suggestion
		glog.V(100).Infof("The tolerations list is empty")
```

2024-07-16 18:37 UTC, achuzhoy commented on pkg/lso/localvolumeset.go
> +	glog.V(100).Infof("Initializing new %s localVolumeSet structure in %s namespace",
```suggestion
	glog.V(100).Infof("Initializing new localVolumeSet %s structure in namespace %s",
```

2024-07-16 22:29 UTC, achuzhoy submitted a review, later dismissed

2024-07-16 22:29 UTC, achuzhoy commented
/lgtm

2024-07-17 14:46 UTC, kononovn requested changes
1 comment to fix

2024-07-17 14:46 UTC, kononovn commented on pkg/lso/localvolumeset_test.go
> +			expectedError:      fmt.Errorf("localVolumeSet cannot be deleted because it does not exist"),
Please update Delete function.
We don't return error if object doesn't exist. Just print log message and return nil. 
Please refer to:
https://github.com/openshift-kni/eco-goinfra/blob/82c1862d9c98d00fac446c4bf84d37ca5ac36e08/pkg/argocd/applications.go#L162

2024-07-17 15:05 UTC, kononovn approved these changes
/lgtm

2024-07-17 15:10 UTC, merged