clusterlogging pkg: objectBucketClaim object handler added
openshift-kni/eco-goinfra pull request #502
Opened 2024-07-05 23:40 UTC by elenagerman

2024-07-10 03:23 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-15 15:06 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-15 19:58 UTC, kononovn commented on pkg/clusterlogging/objectbucketclaim.go
> +type ObjectBucketClaimBuilder struct {
According to the documentation this is storage object.
https://rook.io/docs/rook/latest-release/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/
I think this object has to be under storage package.

2024-07-15 20:28 UTC, kononovn requested changes
Looks good just few comments to fix.

2024-07-15 20:28 UTC, kononovn commented on pkg/clusterlogging/objectbucketclaim.go
> +	glog.V(100).Infof("Deleting the objectBucketClaim %s in namespace %s",
Deleting the objectBucketClaim %s from namespace %s",

2024-07-15 20:28 UTC, kononovn commented on pkg/clusterlogging/objectbucketclaim_test.go
> +
1 test case missing. Please add TestObjectBucketClaimWithGenerateBucketName

2024-07-16 14:50 UTC, kononovn submitted a review, later dismissed
/lgtm

2024-07-17 16:01 UTC, trewest commented on pkg/storage/objectbucketclaim.go
> +	}
```suggestion
	builder.Object = builder.Definition
```

2024-07-19 13:43 UTC, merged