clusterlogging pkg: IsReady method added to the lokistack handler
openshift-kni/eco-goinfra pull request #512
Opened 2024-07-15 01:06 UTC by elenagerman

2024-07-15 15:07 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-15 17:49 UTC, achuzhoy commented on pkg/clusterlogging/lokistack.go
> +// IsReady check if the lokiStack state is Ready.
```suggestion
// IsReady checks for the duration of timeout if the lokiStack state is Ready.
```

2024-07-15 17:58 UTC, achuzhoy commented
We'll need a test for it too.

2024-07-15 17:59 UTC, achuzhoy submitted a review, later dismissed

2024-07-15 17:59 UTC, achuzhoy commented
/lgtm

2024-07-16 15:55 UTC, kononovn requested changes
looks good. Please add test case for this function

2024-07-16 17:32 UTC, kononovn approved these changes
/lgtm

2024-07-16 17:32 UTC, merged