clusterlogging pkg: IsReady method added to the clusterlogging handler
openshift-kni/eco-goinfra pull request #513
Opened 2024-07-15 01:14 UTC by elenagerman

2024-07-15 15:07 UTC, elenagerman commented
@trewest @kononovn @achuzhoy @cdvultur PTAL

2024-07-15 17:54 UTC, achuzhoy commented on pkg/clusterlogging/clusterlogging.go
> +// IsReady check if the clusterLogging instance state is Ready.
```suggestion
// IsReady checks for the duration of timeout if the clusterLogging instance state is Ready.
```

2024-07-16 15:52 UTC, kononovn approved these changes
/lgtm

2024-07-16 15:54 UTC, kononovn requested changes
Looks good. Please add test case for this function

2024-07-16 17:32 UTC, kononovn approved these changes
/lgtm

2024-07-16 17:32 UTC, merged