ocm: added unit tests and increased coverage
openshift-kni/eco-goinfra pull request #547
Opened 2024-07-30 16:40 UTC by klaskosk

Closes #544 by adding unit tests for the list and validate functions in the OCM package and modifying a few existing test cases to improve coverage a bit. This PR also resets the resourceversion during force updates to preemptively address situations like in #483.

2024-07-30 18:39 UTC, kononovn commented
@klaskosk Please keep PRs small. PR is too big for review. Please split it by types:
policy.go
policy_test.go
policylist.go
policylist_test.go
 same for policyset and so on.

2024-07-30 18:39 UTC, kononovn requested changes
PR is too big for review. Please split

2024-07-30 20:17 UTC, klaskosk commented
@kononovn I've gone ahead and split out each type to be #550, #551, #552, and #553 and have left this to just be the updates to the remaining resources. These new PRs should be a much more manageable size

2024-07-31 14:40 UTC, kononovn approved these changes
/lgtm

2024-07-31 14:40 UTC, merged