scc: switch to runtime client, added unit tests
openshift-kni/eco-goinfra pull request #653
Opened 2024-09-10 16:11 UTC by kononovn

2024-09-10 16:34 UTC, klaskosk approved these changes
/lgtm

2024-09-11 16:10 UTC, trewest commented on pkg/scc/scc.go
> +		return nil, fmt.Errorf("failed to add nmstate v1 scheme to client schemes")
```suggestion
		return nil, fmt.Errorf("failed to add security v1 scheme to client schemes")
```

2024-09-11 16:14 UTC, trewest requested changes
Looks good just one small comment

2024-09-11 18:26 UTC, klaskosk approved these changes

2024-09-11 18:27 UTC, merged