Added GetInterfaceType to NMState pkg
openshift-kni/eco-goinfra pull request #68
Opened 2023-07-21 17:17 UTC by evgenLevin

2023-07-24 19:57 UTC, kononovn commented on pkg/nmstate/shared.go
> +// Bridge provides struct for the NMState Interface Ethernet  Bridge state object
Please remove double space

2023-07-24 19:57 UTC, kononovn commented on pkg/nmstate/shared.go
> +// LinkAggregation provides struct for the NMState Interface Ethernet  LinkAggregation state object
Please remove 2 spaces

2023-07-24 19:58 UTC, kononovn commented on pkg/nmstate/shared.go
> +// OptionsLinkAggregation provides struct for the NMState Interface Ethernet  LinkAggregation Options state object
Please remove 2 spaces

2023-07-24 19:58 UTC, kononovn commented on pkg/nmstate/shared.go
> +// Vlan provides struct for the NMState Interface Ethernet  Vlan Options state object
Please remove 2 spaces

2023-07-24 19:59 UTC, kononovn requested changes
Please fix few comments

2023-07-24 20:26 UTC, kononovn approved these changes
lgtm

2023-07-25 10:51 UTC, cdvultur commented
/lgtm

2023-07-25 12:48 UTC, merged

2023-07-25 12:55 UTC, evgenLevin commented
@cdvultur Thanks!!!