Added WithHostNetwork func to the pod pkg
openshift-kni/eco-goinfra pull request #81
Opened 2023-07-29 19:22 UTC by evgenLevin

2023-07-30 01:40 UTC, kononovn commented on pkg/pod/pod.go
> +	glog.V(100).Infof("Defining pod's HostNetwork")
Please change logs to 
glog.V(100).Infof("Applying HostNetwork flag to pod's %s configuration", builder.Definition.Name)

2023-07-30 01:40 UTC, kononovn requested changes
Just 1 small comment.

2023-07-31 01:57 UTC, evgenLevin commented
@kononovn PTAL

2023-07-31 02:30 UTC, kononovn approved these changes
lgtm

2023-07-31 02:30 UTC, merged